name: Deploy Docs

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Tag or branch to build docs from"
        required: true
        default: "develop"

jobs:
  docs:
    permissions:
      contents: write
    uses: bloomreach-forge/ci-workflows/.github/workflows/build-gh-pages.yml@v2.0.0
    with:
      ref: ${{ inputs.ref }}
      site-profile: github.pages
    secrets:
      BR_MAVEN_USERNAME: ${{ secrets.BR_MAVEN_USERNAME }}
      BR_MAVEN_PASSWORD: ${{ secrets.BR_MAVEN_PASSWORD }}

  configure-pages:
    needs: docs
    permissions:
      pages: write
    uses: bloomreach-forge/ci-workflows/.github/workflows/configure-gh-pages.yml@v2.0.0
